version: 2

# Use this if you are referencing modules from a private module registry.
registries:
  hcp-terraform:
    type: terraform-registry
    url: https://app.terraform.io # Update this to a custom hostname if needed.
    token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

updates:
- package-ecosystem: terraform
  directory: /
  registries: '*'
  schedule:
    interval: weekly

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
